---
name: Run build ant tests
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    name: run build and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build library
        run: make
      - name: run tests
        run: make test
